name: Create Pull Request
on:
  workflow_dispatch:

jobs:
  create-pr:
    uses: priya-kinthali/versions-package-tools/.github/workflows/create-pr-to-update-manifest.yml@test-319
    with:
      tool-name: "python"
    secrets: inherit
